// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// NOTE: We load `.env.local` (not `.env`) to match Next.js convention.
// This makes prisma.config.ts work whether you run via our npm scripts
// (which use dotenv-cli) or invoke prisma directly.
loadEnv({ path: ".env.local" });

if (!process.env.DATABASE_URL) {
  // WHY: Fail loudly at config load if DATABASE_URL is missing. Better than
  // a confusing connection error from deep inside Prisma's internals.
  throw new Error("DATABASE_URL is not set. Check .env.local.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
