/**
 * Transaction reference generation.
 *
 * The reference is the IDEMPOTENCY ANCHOR for every transaction:
 * - We generate it once when initiating a payment.
 * - We send it to Paystack as their `reference` field.
 * - We use it as the UNIQUE column in our `transactions` table.
 * - If a webhook arrives twice with the same reference, the second INSERT
 *   fails at the database level. No race, no double-credit.
 *
 * Format: "<source>_<random>" — e.g. "topup_a1b2c3d4e5f6..."
 * The prefix makes references human-debuggable in logs and DB inspection.
 *
 * WHY 16 random bytes: 128 bits of entropy. The chance of collision across
 * all references ever generated by all kobo-wallet instances is effectively
 * zero. Standard cryptographic practice.
 */

import { randomBytes } from "node:crypto";

const VALID_SOURCES = ["topup", "debit", "refund", "reversal"] as const;
type Source = (typeof VALID_SOURCES)[number];

/**
 * Generate a transaction reference with a source prefix.
 *
 * @example
 *   generateReference("topup")  // → "topup_a1b2c3d4e5f6789012345678901234ab"
 *   generateReference("debit")  // → "debit_..."
 */
export function generateReference(source: Source): string {
  // WHY hex over base64: hex is URL-safe, case-insensitive, and plays nicely
  // with both humans and tools. Slightly longer than base64 but that's fine.
  const random = randomBytes(16).toString("hex");
  return `${source}_${random}`;
}